language: node_js
node_js:
  - "4.6"
  - "6.9"
  - "7.2"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
after_script:
  - yarn report-coverage
deploy: 
  provider: heroku
  api_key: 37a3cb7f-3050-4ef5-b6a0-51bec40789b4
  app: sbapi